<?php

return [
    [
        'name'        => 'public_url',
        'label'       => 'B 站公网地址',
        'type'        => 'string',
        'required'    => true,
        'rules'       => ['required', 'url', 'max:255'],
        'description' => '当前 B 站根地址；生产环境必须为 HTTPS，本地或测试环境可使用 HTTP。',
    ],
    [
        'name'        => 'a_site_url',
        'label'       => 'A 站公网地址',
        'type'        => 'string',
        'required'    => true,
        'rules'       => ['required', 'url', 'max:255'],
        'description' => '允许发起支付请求和接收回调的 A 站根地址；生产环境必须为 HTTPS，本地或测试环境可使用 HTTP。',
    ],
    [
        'name'        => 'merchant_display_name',
        'label'       => 'B 站收款主体名称',
        'type'        => 'string',
        'required'    => true,
        'rules'       => ['required', 'string', 'max:127'],
        'description' => '必须与消费者看到并由 PayPal 审核的真实收款主体一致。',
    ],
    [
        'name'        => 'customer_service_email',
        'label'       => 'B 站客服邮箱',
        'type'        => 'string',
        'required'    => true,
        'rules'       => ['required', 'email', 'max:255'],
        'description' => '显示在 B 站支付页，由 B 站负责付款、退款和争议咨询。',
    ],
    [
        'name'        => 'customer_service_phone',
        'label'       => 'B 站客服电话',
        'type'        => 'string',
        'required'    => false,
        'rules'       => ['nullable', 'string', 'max:64'],
    ],
    [
        'name'        => 'refund_policy_url',
        'label'       => 'B 站退款政策地址',
        'type'        => 'string',
        'required'    => true,
        'rules'       => ['required', 'url', 'max:1000'],
        'description' => '生产环境必须是 B 站同域 HTTPS 页面；本地或测试环境可使用 HTTP。',
    ],
    [
        'name'        => 'privacy_policy_url',
        'label'       => 'B 站隐私政策地址',
        'type'        => 'string',
        'required'    => true,
        'rules'       => ['required', 'url', 'max:1000'],
        'description' => '生产环境必须是 B 站同域 HTTPS 页面；本地或测试环境可使用 HTTP。',
    ],
    [
        'name'        => 'terms_url',
        'label'       => 'B 站交易条款地址',
        'type'        => 'string',
        'required'    => true,
        'rules'       => ['required', 'url', 'max:1000'],
        'description' => '生产环境必须是 B 站同域 HTTPS 页面；本地或测试环境可使用 HTTP。',
    ],
    [
        'name'        => 'a_request_verification_secret',
        'label'       => 'A 请求验签密钥',
        'type'        => 'string',
        'required'    => true,
        'rules'       => ['required', 'string', 'min:32', 'max:512'],
        'description' => '必须与 A 站的“A 到 B 请求签名密钥”完全一致。',
    ],
    [
        'name'        => 'a_callback_signing_secret',
        'label'       => 'A 回调签名密钥',
        'type'        => 'string',
        'required'    => true,
        'rules'       => ['required', 'string', 'min:32', 'max:512'],
        'description' => '必须与 A 站的“B 到 A 回调验签密钥”完全一致，且不可与上一项复用。',
    ],
    [
        'name'        => 'request_timeout_seconds',
        'label'       => '网络请求超时',
        'type'        => 'string',
        'required'    => true,
        'rules'       => ['required', 'integer', 'min:3', 'max:30'],
        'description' => '单位：秒。适用于 PayPal API 和 B 到 A 的签名回调。',
    ],
    [
        'name'      => 'sandbox_mode',
        'label'     => 'PayPal 沙盒模式',
        'type'      => 'select',
        'options'   => [
            ['value' => '1', 'label' => '沙盒'],
            ['value' => '0', 'label' => '正式环境'],
        ],
        'required'    => true,
        'rules'       => ['required', 'boolean'],
        'description' => 'B 站所有自动账号统一使用该环境；沙盒账号不能用于正式收款。',
    ],
    [
        'name'      => 'card_enabled',
        'label'     => '允许信用卡收款',
        'type'      => 'select',
        'options'   => [
            ['value' => '1', 'label' => '启用'],
            ['value' => '0', 'label' => '停用'],
        ],
        'required'    => true,
        'rules'       => ['required', 'boolean'],
        'description' => '允许 B 站加载 PayPal Card Fields。所有自动轮询账号都应具备 Advanced Card Payments 资格。',
    ],
    [
        'name'      => 'wallet_enabled',
        'label'     => '允许 PayPal 钱包收款',
        'type'      => 'select',
        'options'   => [
            ['value' => '1', 'label' => '启用'],
            ['value' => '0', 'label' => '停用'],
        ],
        'required'    => true,
        'rules'       => ['required', 'boolean'],
        'description' => '允许 B 站创建 PayPal 钱包授权会话。',
    ],
    [
        'name'        => 'account_cooldown_minutes',
        'label'       => '账号失败冷却时间',
        'type'        => 'string',
        'required'    => true,
        'rules'       => ['required', 'integer', 'min:1', 'max:1440'],
        'description' => '单位：分钟。只对连接失败和 PayPal 5xx 生效；4xx、合规拒绝和账号限制不会自动换号。',
    ],
    [
        'name'      => 'status',
        'label'     => '启用插件',
        'type'      => 'select',
        'options'   => [
            ['value' => '1', 'label' => '启用'],
            ['value' => '0', 'label' => '停用'],
        ],
        'required' => true,
        'rules'    => ['required', 'boolean'],
    ],
];
