<?php

/**
 * 广告追踪插件设置字段，字段值由 BeikeShop settings 表统一保存。
 */

return [
    [
        'name'     => 'enabled_events',
        'label'    => 'Enabled events',
        'type'     => 'checkbox',
        'required' => false,
        'rules'    => 'nullable|array',
    ],
    [
        'name'   => 'consent_mode',
        'label'  => 'Consent mode',
        'type'   => 'select',
        'options' => [
            ['value' => 'opt_in', 'label' => 'Opt-in'],
            ['value' => 'always', 'label' => 'Always load'],
        ],
        'required' => true,
        'rules' => 'required|in:opt_in,always',
    ],
    [
        'name'     => 'facebook_pixel_id',
        'label'    => 'Facebook Pixel ID',
        'type'     => 'string',
        'required' => false,
        'rules'    => 'nullable|string|max:100',
    ],
    [
        'name'     => 'facebook_pixel_ids',
        'label'    => 'Facebook Pixel IDs',
        'type'     => 'textarea',
        'required' => false,
        'rules'    => 'nullable|string|max:5000',
    ],
    [
        'name'     => 'facebook_dispatch_mode',
        'label'    => 'Facebook Dispatch Mode',
        'type'     => 'select',
        'options'  => [
            ['value' => 'single', 'label' => 'Single'],
            ['value' => 'broadcast', 'label' => 'Broadcast'],
            ['value' => 'failover', 'label' => 'Failover'],
        ],
        'required' => true,
        'rules'    => 'required|in:single,broadcast,failover',
    ],
    [
        'name'     => 'facebook_access_token',
        'label'    => 'Facebook Conversion API Token',
        'type'     => 'string',
        'required' => false,
        'rules'    => 'nullable|string|max:5000',
    ],
    [
        'name' => 'facebook_enabled',
        'label' => 'Facebook enabled',
        'type' => 'bool',
        'required' => false,
        'rules' => 'nullable|boolean',
    ],
    [
        'name' => 'facebook_browser',
        'label' => 'Facebook browser events',
        'type' => 'bool',
        'required' => false,
        'rules' => 'nullable|boolean',
    ],
    [
        'name' => 'facebook_server',
        'label' => 'Facebook server events',
        'type' => 'bool',
        'required' => false,
        'rules' => 'nullable|boolean',
    ],
    [
        'name'     => 'google_ads_id',
        'label'    => 'Google Ads ID',
        'type'     => 'string',
        'required' => false,
        'rules'    => 'nullable|string|max:100',
    ],
    [
        'name'     => 'google_ads_label',
        'label'    => 'Google Ads Conversion Label',
        'type'     => 'string',
        'required' => false,
        'rules'    => 'nullable|string|max:200',
    ],
    [
        'name'     => 'google_tag_manager_id',
        'label'    => 'Google Tag Manager ID',
        'type'     => 'string',
        'required' => false,
        'rules'    => 'nullable|string|max:100',
    ],
    [
        'name' => 'google_ads_enabled',
        'label' => 'Google Ads enabled',
        'type' => 'bool',
        'required' => false,
        'rules' => 'nullable|boolean',
    ],
    [
        'name' => 'google_ads_browser',
        'label' => 'Google Ads browser events',
        'type' => 'bool',
        'required' => false,
        'rules' => 'nullable|boolean',
    ],
    [
        'name'     => 'ga4_measurement_id',
        'label'    => 'GA4 Measurement ID',
        'type'     => 'string',
        'required' => false,
        'rules'    => 'nullable|string|max:100',
    ],
    [
        'name'     => 'ga4_api_secret',
        'label'    => 'GA4 Measurement Protocol Secret',
        'type'     => 'string',
        'required' => false,
        'rules'    => 'nullable|string|max:500',
    ],
    [
        'name' => 'ga4_enabled',
        'label' => 'GA4 enabled',
        'type' => 'bool',
        'required' => false,
        'rules' => 'nullable|boolean',
    ],
    [
        'name' => 'ga4_browser',
        'label' => 'GA4 browser events',
        'type' => 'bool',
        'required' => false,
        'rules' => 'nullable|boolean',
    ],
    [
        'name' => 'ga4_server',
        'label' => 'GA4 server events',
        'type' => 'bool',
        'required' => false,
        'rules' => 'nullable|boolean',
    ],
    [
        'name'     => 'tiktok_pixel_id',
        'label'    => 'TikTok Pixel ID',
        'type'     => 'string',
        'required' => false,
        'rules'    => 'nullable|string|max:100',
    ],
    [
        'name'     => 'tiktok_access_token',
        'label'    => 'TikTok Events API Token',
        'type'     => 'string',
        'required' => false,
        'rules'    => 'nullable|string|max:5000',
    ],
    [
        'name' => 'tiktok_enabled',
        'label' => 'TikTok enabled',
        'type' => 'bool',
        'required' => false,
        'rules' => 'nullable|boolean',
    ],
    [
        'name' => 'tiktok_browser',
        'label' => 'TikTok browser events',
        'type' => 'bool',
        'required' => false,
        'rules' => 'nullable|boolean',
    ],
    [
        'name' => 'tiktok_server',
        'label' => 'TikTok server events',
        'type' => 'bool',
        'required' => false,
        'rules' => 'nullable|boolean',
    ],
    [
        'name'     => 'twitter_pixel_id',
        'label'    => 'Twitter / X Pixel ID',
        'type'     => 'string',
        'required' => false,
        'rules'    => 'nullable|string|max:100',
    ],
    [
        'name' => 'twitter_enabled',
        'label' => 'Twitter enabled',
        'type' => 'bool',
        'required' => false,
        'rules' => 'nullable|boolean',
    ],
    [
        'name' => 'twitter_browser',
        'label' => 'Twitter browser events',
        'type' => 'bool',
        'required' => false,
        'rules' => 'nullable|boolean',
    ],
    [
        'name'     => 'pinterest_tag_id',
        'label'    => 'Pinterest Tag ID',
        'type'     => 'string',
        'required' => false,
        'rules'    => 'nullable|string|max:100',
    ],
    [
        'name' => 'pinterest_enabled',
        'label' => 'Pinterest enabled',
        'type' => 'bool',
        'required' => false,
        'rules' => 'nullable|boolean',
    ],
    [
        'name' => 'pinterest_browser',
        'label' => 'Pinterest browser events',
        'type' => 'bool',
        'required' => false,
        'rules' => 'nullable|boolean',
    ],
    [
        'name'     => 'postback_url',
        'label'    => 'Custom Postback URL',
        'type'     => 'string',
        'required' => false,
        'rules'    => 'nullable|url|max:2000',
    ],
    [
        'name'     => 'postback_method',
        'label'    => 'Custom Postback Method',
        'type'     => 'select',
        'options'  => [
            ['value' => 'POST', 'label' => 'POST'],
            ['value' => 'GET', 'label' => 'GET'],
        ],
        'required' => true,
        'rules'    => 'required|in:GET,POST',
    ],
    [
        'name'     => 'postback_headers',
        'label'    => 'Custom Postback Headers',
        'type'     => 'textarea',
        'required' => false,
        'rules'    => 'nullable|string|max:5000',
    ],
    [
        'name'     => 'postback_events',
        'label'    => 'Custom Postback Events',
        'type'     => 'string',
        'required' => false,
        'rules'    => 'nullable|string|max:500',
    ],
    [
        'name' => 'postback_enabled',
        'label' => 'Postback enabled',
        'type' => 'bool',
        'required' => false,
        'rules' => 'nullable|boolean',
    ],
    [
        'name' => 'postback_server',
        'label' => 'Postback server events',
        'type' => 'bool',
        'required' => false,
        'rules' => 'nullable|boolean',
    ],
];
