<?php

return [
    [
        'name'        => 'public_url',
        'label'       => 'A 站公网地址',
        'type'        => 'string',
        'required'    => true,
        'rules'       => ['required', 'url', 'max:255'],
        'description' => 'PayPal B 回跳和服务端通知使用的 A 站根地址；生产环境必须为 HTTPS，本地或测试环境可使用 HTTP。',
    ],
    [
        'name'        => 'b_site_url',
        'label'       => 'B 站网关地址',
        'type'        => 'string',
        'required'    => true,
        'rules'       => ['required', 'url', 'max:255'],
        'description' => '安装 PaypalB 的 B 站根地址；生产环境必须为 HTTPS，本地或测试环境可使用 HTTP。',
    ],
    [
        'name'        => 'request_signing_secret',
        'label'       => 'A 到 B 请求签名密钥',
        'type'        => 'string',
        'required'    => true,
        'rules'       => ['required', 'string', 'min:32', 'max:512'],
        'description' => '必须与 B 站的“A 请求验签密钥”完全一致。请使用至少 32 位的随机值。',
    ],
    [
        'name'        => 'callback_verification_secret',
        'label'       => 'B 到 A 回调验签密钥',
        'type'        => 'string',
        'required'    => true,
        'rules'       => ['required', 'string', 'min:32', 'max:512'],
        'description' => '必须与 B 站的“A 回调签名密钥”完全一致，且不要复用上一项密钥。',
    ],
    [
        'name'        => 'payment_expiration_minutes',
        'label'       => '支付会话有效期',
        'type'        => 'string',
        'required'    => true,
        'rules'       => ['required', 'integer', 'min:5', 'max:120'],
        'description' => '单位：分钟。过期会话不可再次付款，重新进入支付页会创建新的会话。',
    ],
    [
        'name'        => 'wallet_enabled',
        'label'       => '启用 PayPal 钱包付款',
        'type'        => 'select',
        'options'     => [
            ['value' => '1', 'label' => '启用'],
            ['value' => '0', 'label' => '停用'],
        ],
        'required'    => true,
        'rules'       => ['required', 'boolean'],
        'description' => '显示 PayPal 账户/钱包付款选项。',
    ],
    [
        'name'        => 'card_enabled',
        'label'       => '启用信用卡付款',
        'type'        => 'select',
        'options'     => [
            ['value' => '1', 'label' => '启用'],
            ['value' => '0', 'label' => '停用'],
        ],
        'required'    => true,
        'rules'       => ['required', 'boolean'],
        'description' => '通过 PayPal Card Fields 展示信用卡/借记卡付款。还需要在 B 站启用信用卡收款并满足 PayPal 账号资格。',
    ],
    [
        'name'        => 'bridge_item_source',
        'label'       => '订单商品明细模式',
        'type'        => 'select',
        'options'     => [
            ['value' => 'a_order', 'label' => '原商品明细'],
            ['value' => 'mapped', 'label' => '映射商品明细'],
        ],
        'required'    => true,
        'rules'       => ['required', 'in:a_order,mapped'],
        'description' => '映射模式使用 CyberCloak 当前已发布且已确认的商品映射，仅替换提交给 PayPal 的商品名称和 SKU；价格、数量、币种和本地订单保持不变。',
    ],
    [
        'name'        => 'request_timeout_seconds',
        'label'       => 'B 站请求超时',
        'type'        => 'string',
        'required'    => true,
        'rules'       => ['required', 'integer', 'min:3', 'max:30'],
        'description' => '单位：秒。仅限制 A 到 B 的服务端请求，不影响 PayPal 买家支付时间。',
    ],
    [
        'name'      => 'status',
        'label'     => '启用插件',
        'type'      => 'select',
        'options'   => [
            ['value' => '1', 'label' => '启用'],
            ['value' => '0', 'label' => '停用'],
        ],
        'required' => true,
        'rules'    => ['required', 'boolean'],
    ],
];
