<?php

return [
    [
        'name'            => 'host',
        'label_key'       => 'setting.host',
        'type'            => 'string',
        'required'        => true,
        'placeholder'     => 'http://meilisearch:7700',
        'description_key' => 'setting.host_description',
    ],
    [
        'name'            => 'api_key',
        'label_key'       => 'setting.api_key',
        'type'            => 'string',
        'required'        => false,
        'description_key' => 'setting.api_key_description',
    ],
    [
        'name'        => 'index_prefix',
        'label_key'   => 'setting.index_prefix',
        'type'        => 'string',
        'required'    => true,
        'placeholder' => 'beikeshop',
    ],
    [
        'name'            => 'timeout',
        'label_key'       => 'setting.timeout',
        'type'            => 'string',
        'required'        => true,
        'placeholder'     => '1',
        'description_key' => 'setting.timeout_description',
    ],
    [
        'name'        => 'batch_size',
        'label_key'   => 'setting.batch_size',
        'type'        => 'string',
        'required'    => true,
        'placeholder' => '300',
    ],
    [
        'name'      => 'search_sort',
        'label_key' => 'setting.search_sort',
        'type'      => 'select',
        'options'   => [
            ['value' => 'latest', 'label_key' => 'setting.sort_latest'],
            ['value' => 'views', 'label_key' => 'setting.sort_views'],
            ['value' => 'sales', 'label_key' => 'setting.sort_sales'],
            ['value' => 'default', 'label_key' => 'setting.sort_default'],
            ['value' => 'updated', 'label_key' => 'setting.sort_updated'],
            ['value' => 'relevance', 'label_key' => 'setting.sort_relevance'],
        ],
        'required'        => true,
        'description_key' => 'setting.search_sort_description',
    ],
    [
        'name'      => 'trending_sort',
        'label_key' => 'setting.trending_sort',
        'type'      => 'select',
        'options'   => [
            ['value' => 'latest', 'label_key' => 'setting.sort_latest'],
            ['value' => 'views', 'label_key' => 'setting.sort_views'],
            ['value' => 'sales', 'label_key' => 'setting.sort_sales'],
            ['value' => 'default', 'label_key' => 'setting.sort_default'],
            ['value' => 'updated', 'label_key' => 'setting.sort_updated'],
            ['value' => 'relevance', 'label_key' => 'setting.sort_relevance'],
        ],
        'required'        => true,
        'description_key' => 'setting.trending_sort_description',
    ],
    [
        'name'      => 'search_enabled',
        'label_key' => 'setting.search_enabled',
        'type'      => 'select',
        'options'   => [
            ['value' => '0', 'label_key' => 'setting.disabled'],
            ['value' => '1', 'label_key' => 'setting.enabled'],
        ],
        'required'        => true,
        'description_key' => 'setting.search_enabled_description',
    ],
    [
        'name'      => 'mysql_fallback',
        'label_key' => 'setting.mysql_fallback',
        'type'      => 'select',
        'options'   => [
            ['value' => '1', 'label_key' => 'setting.enabled'],
            ['value' => '0', 'label_key' => 'setting.disabled'],
        ],
        'required'        => true,
        'description_key' => 'setting.mysql_fallback_description',
    ],
    [
        'name'      => 'category_search',
        'label_key' => 'setting.category_search',
        'type'      => 'select',
        'options'   => [
            ['value' => '1', 'label_key' => 'setting.enabled'],
            ['value' => '0', 'label_key' => 'setting.disabled'],
        ],
        'required'        => true,
        'description_key' => 'setting.category_search_description',
    ],
];
